/*** seeders/20190203043905-Burger.js

Generated by Sequelize CLI.

```
$ node_modules/.bin/sequelize seed:generate --name Burger
```

Run

```
node_modules/.bin/sequelize db:seed:all
```

Undo

```
node_modules/.bin/sequelize db:seed:undo:all
```

[Reference: Creating First Model (And Migration)](http://docs.sequelizejs.com/manual/tutorial/migrations.html#creating-first-model-and-migration-)
[Reference: Running Seeds](http://docs.sequelizejs.com/manual/tutorial/migrations.html#running-seeds)
[Reference: Undoing Seeds](http://docs.sequelizejs.com/manual/tutorial/migrations.html#undoing-seeds)

***/

'use strict';


module.exports = {


    /*** FUNCTION up()

    Add altering commands here.
    Return a promise to correctly handle asynchronicity.

    Example:
    return queryInterface.bulkInsert('People', [{
        name: 'John Doe',
        isBetaMember: false
    }], {});

    */

    up: (queryInterface, Sequelize) => {

        return queryInterface.bulkInsert(
            'Burgers' ,
            [
                {
                    burgerName: 'BurgerFi' ,
                    isDevoured: false ,
                    createdAt: new Date() ,
                    updatedAt: new Date()
                } ,
                {
                    burgerName: 'Chelino\'s' ,
                    isDevoured: false ,
                    createdAt: new Date() ,
                    updatedAt: new Date()
                } ,
                {
                    burgerName: 'Los Verdes' ,
                    isDevoured: false ,
                    createdAt: new Date() ,
                    updatedAt: new Date()
                } ,
                {
                    burgerName: 'Pincho Factory' ,
                    isDevoured: false ,
                    createdAt: new Date() ,
                    updatedAt: new Date()
                }
            ] ,
            {}
        );
    } ,


    /*** FUNCTION down()

    Add reverting commands here.
    Return a promise to correctly handle asynchronicity.

    Example:
    return queryInterface.bulkDelete('People', null, {});

    */

    down: (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete( 'Burgers' , null , {} );
    }

};

