/*** models/burger.js

Generated by Sequelize CLI.

```
$ node_modules/.bin/sequelize model:create --name Burger --attributes burgerName:string,isDevoured:boolean
```

[Reference](http://docs.sequelizejs.com/manual/tutorial/migrations.html#creating-first-model-and-migration-)

***/

'use strict';
module.exports = (sequelize, DataTypes) => {
  const Burger = sequelize.define('Burger', {
    burgerName: DataTypes.STRING,
    isDevoured: DataTypes.BOOLEAN
  }, {});
  Burger.associate = function(models) {
    // associations can be defined here
  };
  return Burger;
};
